### ISSUE TITLE
Implement color filter

### ISSUE THREAD

**Issue by erchaves** [mplusmuseum/mplusmuseum-collections-explorer#14]
Exact behavior TBD. Please confirm with @revdancatt about how the API works to support this.

Please see design. 
![screen shot 2018-11-20 at 8 31 37 pm](https://user-images.githubusercontent.com/302309/48813088-4e59e880-ed03-11e8-9b01-aac19fd73808.png)

I'm marking this as a low priority for now to make sure we get everything else done.

**Comment by erchaves** [comment]
Please note this conversation from slack:

davealma [10:51 AM]
But one colour at the time? Because on the pdf it feels like we could search by more than one colour at the time

revdancatt [10:52 AM]
Yeah, I think just one colour at a time, just to keep things simple at the moment.
I’m going to do a colour search within 30 “degrees” of the hue picked, i.e. picking orange (at hue 60, will find everything in the range 30-90, reddy-orange to orangey-yellow). _Well_ that’s the theory anyway, there’s so few actual images it’s going to be interesting to find out what, if anything, it picks.

**Comment by erchaves** [comment]
@micahwalter The design for this indicates that you can select more than one color at a time, but it sounds like we all think it makes more sense to only choose one color at a time. Do you want to change the design so it makes more sense to choose just one color?  I think we could just remove the color square with the 'X' that makes it look like you can choose multiple. And instead use some other indication of the color you chose.

**Comment by micahwalter** [comment]
I think you should be able to add more than one color. It should be additive.

**Comment by erchaves** [comment]
We discussed this yesterday - the colors should be an "or" search. So in the search results they will be "additive" in that each added color will start also showing up in the results. If you search for red and blue, the search will return any results for red or blue, so it will show both.
