### ISSUE TITLE
Search - basic implementation: Grid view, Search input, and Sort by popular or "newness"

### ISSUE THREAD

**Issue by erchaves** [mplusmuseum/mplusmuseum-collections-explorer#17]
As a first pass, let's implement the search with just these basics.
![screen shot 2018-11-20 at 8 42 17 pm](https://user-images.githubusercontent.com/302309/48813473-1c498600-ed05-11e8-998a-b93a52b8055c.png)

Please see these other tickets about the more advanced features:
https://github.com/mplusmuseum/mplusmuseum-collections-explorer/issues/18

**Comment by davealma** [comment]
Basic search for Grid view is implemented. 
TODO: Sort by popular and newness and sort api to implement by @revdancatt
