### ISSUE TITLE
Implement image zoom and image info UIs

### ISSUE THREAD

**Issue by erchaves** [mplusmuseum/mplusmuseum-collections-explorer#25]
@micahwalter I think we need more clarification about how these should work. 

**Question:** What does the info button do? (maybe i missed this in the design..)
**Question:** What happens when you click the zoom button?

![screen shot 2018-11-20 at 9 14 36 pm](https://user-images.githubusercontent.com/302309/48814642-85cb9380-ed09-11e8-9727-0501e256b804.png)

There is an example of zoom functionality on the barnes website that we built. We can borrow from that code if helpful.
See example. https://collection.barnesfoundation.org/objects/5677/Haere-Pape/details
https://github.com/BarnesFoundation/barnes-collection-www/tree/93b4aea3b812d0780fdab433cc0813160154531a/src/components/Zoom

**Comment by micahwalter** [comment]
@erchaves -- zoom wont be implemented for this first iteration

info button... please make sure you have the latest design work from A&B .. I believe this has changed slightly..
