### ISSUE TITLE
Implement object details page for single object 

### ISSUE THREAD

**Issue by erchaves** [mplusmuseum/mplusmuseum-collections-explorer#27]
Please see design for details. Let us know what information might be missing or non-obvious from the API to support this page.
![screen shot 2018-11-22 at 2 46 00 pm](https://user-images.githubusercontent.com/302309/48920178-5fbb0600-ee65-11e8-8cb7-de2edb75a00a.png)

**Comment by davealma** [comment]
![singleobjectparts](https://user-images.githubusercontent.com/1358986/49178994-edd83600-f316-11e8-9e3a-bacac9adc71a.png)

I have questions about some components.
1) For artist name I get an array of constituents. I don't know if is safe to assume the array will have always one record or should I request a different field.
2) What does symbols represents?
3) TMSID is not present on the response!
4)Accession Number is Object number?
5) About the artist, should I rely on constituents? If that is the case what field should I use for that section?
6) Related Material is not present on the response?
7) what is the apparent name value for the url after the domain? the name in dash case or snake case?
8) What are those links?

**Comment by erchaves** [comment]
Thanks for the detailed questions @davealma, I'll check with Dan about these.
