### ISSUE TITLE
Art object bottom-of-page UI (needs definition)

### ISSUE THREAD

**Issue by erchaves** [mplusmuseum/mplusmuseum-collections-explorer#29]
![screen shot 2018-11-22 at 2 52 48 pm](https://user-images.githubusercontent.com/302309/48920352-6d24c000-ee66-11e8-8190-33e69dd3db6f.png)

These elements need more definition, so I'll assign to Micah for now. 

Questions: 

- link in an input:
  - Is this just the url for copying? Is this inside an input? I assume it's not editable correct?

- Pills:
  - What are these square 'pills'? Are they Collections that the object is in? Does the '...' just reveal more?

- Social:
  - What should the social share buttons do? Open a share dialog? If so, what copy should we use? 
  - I see facebook, twitter, and wechat... what is the last one -- the '+'?

**Comment by micahwalter** [comment]
@erchaves  - the permalink feature should work similar to how it is on a Stories blog post -- see example here - https://stories.mplus.org.hk/en/blog/from-the-collections-untitled-by-wang-xingwei

Clicking on these pills takes you to a new search result for whatever is in the pill... they are the collection and maker the work belongs to.

Yes, the social buttons should allow you to share to the corresponding network.. + can open an expanded list of networks, lets focus on FB, TW and WeChat for now..
