### ISSUE TITLE
Implement header menu ('hamburger' menu)

### ISSUE THREAD

**Issue by erchaves** [mplusmuseum/mplusmuseum-collections-explorer#31]
![screen shot 2018-11-22 at 3 00 10 pm](https://user-images.githubusercontent.com/302309/48920527-63e82300-ee67-11e8-8243-5b7f208cd89b.png)
![screen shot 2018-11-22 at 3 00 23 pm](https://user-images.githubusercontent.com/302309/48920528-63e82300-ee67-11e8-8e7b-dabb088b75c9.png)

@davealma I think this is already implemented on mobile. So we can re-use that logic and just change the styles and breakpoint rules.

**Comment by erchaves** [comment]
Hmm, this was working on mobile before I thought. Let me take a quick look at this later before passing it back to you.

**Comment by davealma** [comment]
Ok @erchaves let me know after you take a look
