### ISSUE TITLE
Email newsletter signup

### ISSUE THREAD

**Issue by erchaves** [mplusmuseum/mplusmuseum-collections-explorer#32]
![screen shot 2018-11-22 at 3 07 19 pm](https://user-images.githubusercontent.com/302309/48920698-5a12ef80-ee68-11e8-9deb-1388af838007.png)

@micahwalter let us know what service we should use. If there is not an existing service and you want us to just setup a new mailchimp account or something let us know.

**Comment by micahwalter** [comment]
Theres an existing service being used for Stories. I’ll get more info and
let you know Monday
