### ISSUE TITLE
Page Meta-Tags

### ISSUE THREAD

**Issue by micahwalter** [mplusmuseum/mplusmuseum-collections-explorer#8]
Each page should have proper meta-tags for SEO. This will be done using the react "helmet" tool. See the file /src/Components/HelmetHeader/index.js. Strings can be added to the META_TAGS constant.

**Comment by erchaves** [comment]
@davealma we should consider how this interacts with internationalization. We should set up the internationalization to actually change the URL to a new language prefix. That way, when we change the language, the new translated meta tags will apply to a new url. We can talk more about this in the future and look at the intl package together.
